version: '3.1'
services:
  wordpress:
    image: docker.io/wordpress:5-php7.3
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
  db:
    image: docker.io/mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: wp
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: wordpress
    volumes:
      - ./data:/var/lib/mysql:rw
  adminer:
    image: docker.io/adminer:latest
    restart: always
    ports:
      - 8081:8080
  phpmyadmin:
    image: docker.io/phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 8082:80
